/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

/**
 *
 * @author inishbashyal
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(true);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        layered_Panel = new javax.swing.JLayeredPane();
        home_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        add_Faculty_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstName_Label = new javax.swing.JLabel();
        loginID_TextField = new javax.swing.JTextField();
        mobileNumber_TextField = new javax.swing.JTextField();
        lastName_Label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        firstName_TextField1 = new javax.swing.JTextField();
        password_Label = new javax.swing.JLabel();
        password_PasswordField = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        gender_Label = new javax.swing.JLabel();
        gender_ComboBox = new javax.swing.JComboBox<>();
        dob_Label = new javax.swing.JLabel();
        dob_TextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        confirmpassword_PasswordField1 = new javax.swing.JPasswordField();
        lastName_TextField1 = new javax.swing.JTextField();
        save_AddFacultyPanel_Button = new javax.swing.JButton();
        reset_AddFacultyPanel_Button = new javax.swing.JButton();
        faculty_List_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        firstNameSearch_Label = new javax.swing.JLabel();
        firstNameSearch_TextField = new javax.swing.JTextField();
        loginIDSearch_Label = new javax.swing.JLabel();
        loginIDSearch_TextField = new javax.swing.JTextField();
        search_FacultyList_Button = new javax.swing.JButton();
        reset_FacultyList_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        facultyList_Table = new javax.swing.JTable();
        new_FacultyList_Button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        add_Student_Panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        courseName_Label = new javax.swing.JLabel();
        semester_ComboBox = new javax.swing.JComboBox<>();
        semester_Label = new javax.swing.JLabel();
        courseName_ComboBox = new javax.swing.JComboBox<>();
        student_FirstName_Label = new javax.swing.JLabel();
        student_FirstName_TextField = new javax.swing.JTextField();
        student_LastName_TextField = new javax.swing.JTextField();
        student_LastName_Label = new javax.swing.JLabel();
        email_Label = new javax.swing.JLabel();
        student_email_TextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        student_Gender_ComboBox = new javax.swing.JComboBox<>();
        student_Password_Label = new javax.swing.JLabel();
        student_Password_PasswordField = new javax.swing.JPasswordField();
        student_ConfirmPassword_Label = new javax.swing.JLabel();
        student_ConfirmPassword_PasswordField = new javax.swing.JPasswordField();
        student_DateOfBirth_Label = new javax.swing.JLabel();
        student_DateOfBirth_TextField = new javax.swing.JTextField();
        student_MobileNumber_Label = new javax.swing.JLabel();
        student_Mobile_TextField = new javax.swing.JTextField();
        parents_Email_Label = new javax.swing.JLabel();
        parents_Email_TextField = new javax.swing.JTextField();
        parents_Mobile_Label = new javax.swing.JLabel();
        parents_mobile_TextField = new javax.swing.JTextField();
        save_AddStudent_Button = new javax.swing.JButton();
        reset_AddStudent_Button = new javax.swing.JButton();
        student_List_Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        firstName_StudentList_Label = new javax.swing.JLabel();
        firstName_StudentList_TextField = new javax.swing.JTextField();
        lastName_StudentList_TextField = new javax.swing.JTextField();
        lastName_StudentList_Label = new javax.swing.JLabel();
        email_StudentList_TextField = new javax.swing.JTextField();
        email_StudentList_Label = new javax.swing.JLabel();
        search_StudentList_Button = new javax.swing.JButton();
        reset_StudentList_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        new_StudentList_Button = new javax.swing.JButton();
        delete_StudentList_Button = new javax.swing.JButton();
        add_Course_Panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        course_List_Panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        add_Subject_Panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        subject_List_Panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        add_Assignment_Faculty_Panel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        assignment_Faculty_List_Panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        dashboard_menuBar = new javax.swing.JMenuBar();
        home_Menu = new javax.swing.JMenu();
        home_MenuItem = new javax.swing.JMenuItem();
        faculty_Menu = new javax.swing.JMenu();
        addFaculty_MenuItem = new javax.swing.JMenuItem();
        FacultyList_MenuItem = new javax.swing.JMenuItem();
        student_Menu = new javax.swing.JMenu();
        AddStudent_MenuItem = new javax.swing.JMenuItem();
        StudentList_MenuItem = new javax.swing.JMenuItem();
        course_Menu = new javax.swing.JMenu();
        AddCourse_MenuItem = new javax.swing.JMenuItem();
        CourseList_MenuItem = new javax.swing.JMenuItem();
        subject_Menu = new javax.swing.JMenu();
        AddSubject_MenuItem = new javax.swing.JMenuItem();
        SubjectList_MenuItem = new javax.swing.JMenuItem();
        assignmentFaculty_Menu = new javax.swing.JMenu();
        AddAssignmentFaculty_MenuItem = new javax.swing.JMenuItem();
        AssignmentFacultyList_MenuItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu7.setText("File");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar2.add(jMenu8);

        jMenuItem11.setText("Ass");

        jMenuItem12.setText("jMenuItem12");

        jMenu9.setText("File");
        jMenuBar3.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar3.add(jMenu10);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("home");

        javax.swing.GroupLayout home_PanelLayout = new javax.swing.GroupLayout(home_Panel);
        home_Panel.setLayout(home_PanelLayout);
        home_PanelLayout.setHorizontalGroup(
                home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(home_PanelLayout.createSequentialGroup()
                                .addGap(395, 395, 395)
                                .addComponent(jLabel1)
                                .addContainerGap(565, Short.MAX_VALUE))
        );
        home_PanelLayout.setVerticalGroup(
                home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(home_PanelLayout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jLabel1)
                                .addContainerGap(279, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Add Faculty");

        firstName_Label.setText("First Name");

        loginID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginID_TextFieldActionPerformed(evt);
            }
        });

        mobileNumber_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumber_TextFieldActionPerformed(evt);
            }
        });

        lastName_Label.setText("Last Name");

        jLabel12.setText("Login ID :");

        firstName_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName_TextField1ActionPerformed(evt);
            }
        });

        password_Label.setText("Password");

        jLabel13.setText("Confirm Password");

        gender_Label.setText("Gender");

        gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gender_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_ComboBoxActionPerformed(evt);
            }
        });

        dob_Label.setText("Date Of Birth");

        dob_TextField.setText("dd/mm/yyyy");

        jLabel14.setText("Mobile Number");

        confirmpassword_PasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassword_PasswordField1ActionPerformed(evt);
            }
        });

        lastName_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastName_TextField1ActionPerformed(evt);
            }
        });

        save_AddFacultyPanel_Button.setBackground(new java.awt.Color(0, 0, 255));
        save_AddFacultyPanel_Button.setForeground(new java.awt.Color(255, 255, 255));
        save_AddFacultyPanel_Button.setText("SAVE");
        save_AddFacultyPanel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_AddFacultyPanel_ButtonActionPerformed(evt);
            }
        });

        reset_AddFacultyPanel_Button.setBackground(new java.awt.Color(0, 0, 255));
        reset_AddFacultyPanel_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_AddFacultyPanel_Button.setText("RESET");

        javax.swing.GroupLayout add_Faculty_PanelLayout = new javax.swing.GroupLayout(add_Faculty_Panel);
        add_Faculty_Panel.setLayout(add_Faculty_PanelLayout);
        add_Faculty_PanelLayout.setHorizontalGroup(
                add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(firstName_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(35, 35, 35)
                                                                .addComponent(firstName_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(loginID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(password_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(gender_Label)
                                                                        .addComponent(password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(dob_Label))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(dob_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                                                .addComponent(save_AddFacultyPanel_Button)
                                                                .addGap(26, 26, 26)))
                                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                                                .addGap(139, 139, 139)
                                                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                                                                .addComponent(jLabel14)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(mobileNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                                                                .addComponent(jLabel13)
                                                                                .addGap(22, 22, 22)
                                                                                .addComponent(confirmpassword_PasswordField1))
                                                                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                                                                .addComponent(lastName_Label)
                                                                                .addGap(70, 70, 70)
                                                                                .addComponent(lastName_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_Faculty_PanelLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(reset_AddFacultyPanel_Button)
                                                                .addGap(345, 345, 345))))
                                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(56, Short.MAX_VALUE))
        );
        add_Faculty_PanelLayout.setVerticalGroup(
                add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Faculty_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstName_Label)
                                        .addComponent(lastName_Label)
                                        .addComponent(firstName_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastName_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(loginID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(password_Label)
                                        .addComponent(password_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addComponent(confirmpassword_PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(gender_Label)
                                        .addComponent(gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dob_Label)
                                        .addComponent(dob_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)
                                        .addComponent(mobileNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(add_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(save_AddFacultyPanel_Button)
                                        .addComponent(reset_AddFacultyPanel_Button))
                                .addGap(24, 24, 24))
        );

        faculty_List_Panel.setPreferredSize(new java.awt.Dimension(988, 472));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("Faculty List");

        firstNameSearch_Label.setText("First Name");

        firstNameSearch_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameSearch_TextFieldActionPerformed(evt);
            }
        });

        loginIDSearch_Label.setText("Login ID");

        loginIDSearch_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIDSearch_TextFieldActionPerformed(evt);
            }
        });

        search_FacultyList_Button.setBackground(new java.awt.Color(0, 0, 255));
        search_FacultyList_Button.setForeground(new java.awt.Color(255, 255, 255));
        search_FacultyList_Button.setText("SEARCH");

        reset_FacultyList_Button.setBackground(new java.awt.Color(0, 0, 255));
        reset_FacultyList_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_FacultyList_Button.setText("RESET");
        reset_FacultyList_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_FacultyList_ButtonActionPerformed(evt);
            }
        });

        facultyList_Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "SELECT ALL", "#", "NAME", "LOGIN ID", "MOBILE NO.", "DATE OF BIRTH", "GENDER", "ACTION"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(facultyList_Table);

        new_FacultyList_Button.setBackground(new java.awt.Color(51, 153, 0));
        new_FacultyList_Button.setForeground(new java.awt.Color(255, 255, 255));
        new_FacultyList_Button.setText("NEW");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DELETE");

        javax.swing.GroupLayout faculty_List_PanelLayout = new javax.swing.GroupLayout(faculty_List_Panel);
        faculty_List_Panel.setLayout(faculty_List_PanelLayout);
        faculty_List_PanelLayout.setHorizontalGroup(
                faculty_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(faculty_List_PanelLayout.createSequentialGroup()
                                .addGroup(faculty_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(faculty_List_PanelLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(faculty_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(faculty_List_PanelLayout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addGroup(faculty_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(faculty_List_PanelLayout.createSequentialGroup()
                                                                                .addGap(9, 9, 9)
                                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(faculty_List_PanelLayout.createSequentialGroup()
                                                                                .addComponent(firstNameSearch_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(firstNameSearch_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(76, 76, 76)
                                                                                .addComponent(loginIDSearch_Label)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(loginIDSearch_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(45, 45, 45)
                                                                                .addComponent(search_FacultyList_Button)
                                                                                .addGap(36, 36, 36)
                                                                                .addComponent(reset_FacultyList_Button))))))
                                        .addGroup(faculty_List_PanelLayout.createSequentialGroup()
                                                .addGap(193, 193, 193)
                                                .addComponent(new_FacultyList_Button)
                                                .addGap(207, 207, 207)
                                                .addComponent(jButton1)))
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        faculty_List_PanelLayout.setVerticalGroup(
                faculty_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(faculty_List_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)
                                .addGroup(faculty_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstNameSearch_Label)
                                        .addComponent(firstNameSearch_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginIDSearch_Label)
                                        .addComponent(loginIDSearch_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(search_FacultyList_Button)
                                        .addComponent(reset_FacultyList_Button))
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(faculty_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(new_FacultyList_Button)
                                        .addComponent(jButton1))
                                .addGap(45, 45, 45))
        );

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Add Student");

        courseName_Label.setText("Course Name");

        semester_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        semester_Label.setText("Semester");

        courseName_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        student_FirstName_Label.setText("First Name");

        student_LastName_Label.setText("Last Name");

        email_Label.setText("Email ID :");

        student_email_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_email_TextFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Gender :");

        student_Gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        student_Password_Label.setText("Password");

        student_ConfirmPassword_Label.setText("Confirm Password");

        student_DateOfBirth_Label.setText("Date of Birth");

        student_DateOfBirth_TextField.setText("dd/mm/yyyy");

        student_MobileNumber_Label.setText("Mobile Number");

        parents_Email_Label.setText("Parent's Email");

        parents_Mobile_Label.setText("Parent's Mobile No.");

        save_AddStudent_Button.setBackground(new java.awt.Color(0, 0, 255));
        save_AddStudent_Button.setForeground(new java.awt.Color(255, 255, 255));
        save_AddStudent_Button.setText("SAVE");

        reset_AddStudent_Button.setBackground(new java.awt.Color(0, 0, 255));
        reset_AddStudent_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_AddStudent_Button.setText("RESET");

        javax.swing.GroupLayout add_Student_PanelLayout = new javax.swing.GroupLayout(add_Student_Panel);
        add_Student_Panel.setLayout(add_Student_PanelLayout);
        add_Student_PanelLayout.setHorizontalGroup(
                add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                        .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(courseName_Label)
                                                                                .addComponent(student_FirstName_Label))
                                                                        .addGap(35, 35, 35)
                                                                        .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(courseName_ComboBox, 0, 290, Short.MAX_VALUE)
                                                                                .addComponent(student_FirstName_TextField)))
                                                                .addComponent(email_Label)
                                                                .addComponent(student_email_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(student_Password_Label)
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(parents_Email_Label)
                                                                                        .addComponent(student_DateOfBirth_Label))))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(student_Password_PasswordField)
                                                                                        .addComponent(student_DateOfBirth_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                                                                        .addComponent(parents_Email_TextField))))
                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                .addGap(88, 88, 88)
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addComponent(student_LastName_Label)
                                                                                .addGap(35, 35, 35)
                                                                                .addComponent(student_LastName_TextField))
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addComponent(jLabel15)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addComponent(student_Gender_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                                .addComponent(semester_Label)
                                                                                .addGap(34, 34, 34)
                                                                                .addComponent(semester_ComboBox, 0, 326, Short.MAX_VALUE))))
                                                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                                                .addGap(68, 68, 68)
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(student_ConfirmPassword_Label)
                                                                        .addComponent(student_MobileNumber_Label)
                                                                        .addComponent(parents_Mobile_Label))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(student_ConfirmPassword_PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                                                        .addComponent(student_Mobile_TextField)
                                                                        .addComponent(parents_mobile_TextField))))))
                                .addGap(79, 79, 79))
                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(save_AddStudent_Button)
                                .addGap(137, 137, 137)
                                .addComponent(reset_AddStudent_Button)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add_Student_PanelLayout.setVerticalGroup(
                add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Student_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(courseName_Label)
                                        .addComponent(semester_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(semester_Label)
                                        .addComponent(courseName_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(student_FirstName_Label)
                                        .addComponent(student_FirstName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(student_LastName_Label)
                                        .addComponent(student_LastName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(email_Label)
                                        .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(student_Gender_ComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(student_email_TextField))
                                .addGap(18, 18, 18)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(student_Password_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(student_Password_Label)
                                        .addComponent(student_ConfirmPassword_Label)
                                        .addComponent(student_ConfirmPassword_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(student_DateOfBirth_Label)
                                        .addComponent(student_DateOfBirth_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(student_MobileNumber_Label)
                                        .addComponent(student_Mobile_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(parents_Email_Label)
                                        .addComponent(parents_Email_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(parents_Mobile_Label)
                                        .addComponent(parents_mobile_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(add_Student_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(save_AddStudent_Button)
                                        .addComponent(reset_AddStudent_Button))
                                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("Student List");

        firstName_StudentList_Label.setText("First Name");

        lastName_StudentList_Label.setText("Last Name");

        email_StudentList_Label.setText("Email");

        search_StudentList_Button.setBackground(new java.awt.Color(0, 0, 255));
        search_StudentList_Button.setForeground(new java.awt.Color(255, 255, 255));
        search_StudentList_Button.setText("SEARCH");

        reset_StudentList_Button.setBackground(new java.awt.Color(0, 0, 255));
        reset_StudentList_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_StudentList_Button.setText("RESET");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "Select All", "#", "Course Name", "Semester", "Roll No.", "Name", "Email", "Date Of Birth", "Gender", "Mobile", "Father Email Id", "Father Mobile", "Action"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        new_StudentList_Button.setBackground(new java.awt.Color(51, 153, 0));
        new_StudentList_Button.setForeground(new java.awt.Color(255, 255, 255));
        new_StudentList_Button.setText("NEW");

        delete_StudentList_Button.setBackground(new java.awt.Color(255, 0, 0));
        delete_StudentList_Button.setForeground(new java.awt.Color(255, 255, 255));
        delete_StudentList_Button.setText("DELETE");

        javax.swing.GroupLayout student_List_PanelLayout = new javax.swing.GroupLayout(student_List_Panel);
        student_List_Panel.setLayout(student_List_PanelLayout);
        student_List_PanelLayout.setHorizontalGroup(
                student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(student_List_PanelLayout.createSequentialGroup()
                                .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(student_List_PanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel5)
                                                                .addGroup(student_List_PanelLayout.createSequentialGroup()
                                                                        .addComponent(firstName_StudentList_Label)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(firstName_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(lastName_StudentList_Label)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(lastName_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(email_StudentList_Label)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(email_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(search_StudentList_Button)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(reset_StudentList_Button)))))
                                        .addGroup(student_List_PanelLayout.createSequentialGroup()
                                                .addGap(224, 224, 224)
                                                .addComponent(new_StudentList_Button)
                                                .addGap(140, 140, 140)
                                                .addComponent(delete_StudentList_Button)))
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        student_List_PanelLayout.setVerticalGroup(
                student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(student_List_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstName_StudentList_Label)
                                        .addComponent(firstName_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastName_StudentList_Label)
                                        .addComponent(lastName_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(email_StudentList_Label)
                                        .addComponent(email_StudentList_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(search_StudentList_Button)
                                        .addComponent(reset_StudentList_Button))
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(student_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(new_StudentList_Button)
                                        .addComponent(delete_StudentList_Button))
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel6.setText("add course");

        javax.swing.GroupLayout add_Course_PanelLayout = new javax.swing.GroupLayout(add_Course_Panel);
        add_Course_Panel.setLayout(add_Course_PanelLayout);
        add_Course_PanelLayout.setHorizontalGroup(
                add_Course_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_Course_PanelLayout.createSequentialGroup()
                                .addContainerGap(459, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(454, 454, 454))
        );
        add_Course_PanelLayout.setVerticalGroup(
                add_Course_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Course_PanelLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(jLabel6)
                                .addContainerGap(257, Short.MAX_VALUE))
        );

        jLabel7.setText("Course List");

        javax.swing.GroupLayout course_List_PanelLayout = new javax.swing.GroupLayout(course_List_Panel);
        course_List_Panel.setLayout(course_List_PanelLayout);
        course_List_PanelLayout.setHorizontalGroup(
                course_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(course_List_PanelLayout.createSequentialGroup()
                                .addGap(421, 421, 421)
                                .addComponent(jLabel7)
                                .addContainerGap(490, Short.MAX_VALUE))
        );
        course_List_PanelLayout.setVerticalGroup(
                course_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(course_List_PanelLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel7)
                                .addContainerGap(277, Short.MAX_VALUE))
        );

        jLabel8.setText("add subject");

        javax.swing.GroupLayout add_Subject_PanelLayout = new javax.swing.GroupLayout(add_Subject_Panel);
        add_Subject_Panel.setLayout(add_Subject_PanelLayout);
        add_Subject_PanelLayout.setHorizontalGroup(
                add_Subject_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Subject_PanelLayout.createSequentialGroup()
                                .addGap(448, 448, 448)
                                .addComponent(jLabel8)
                                .addContainerGap(461, Short.MAX_VALUE))
        );
        add_Subject_PanelLayout.setVerticalGroup(
                add_Subject_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Subject_PanelLayout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jLabel8)
                                .addContainerGap(274, Short.MAX_VALUE))
        );

        jLabel9.setText("subject list");

        javax.swing.GroupLayout subject_List_PanelLayout = new javax.swing.GroupLayout(subject_List_Panel);
        subject_List_Panel.setLayout(subject_List_PanelLayout);
        subject_List_PanelLayout.setHorizontalGroup(
                subject_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subject_List_PanelLayout.createSequentialGroup()
                                .addContainerGap(506, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(406, 406, 406))
        );
        subject_List_PanelLayout.setVerticalGroup(
                subject_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(subject_List_PanelLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel9)
                                .addContainerGap(289, Short.MAX_VALUE))
        );

        jLabel10.setText("add assignment faculty ");

        javax.swing.GroupLayout add_Assignment_Faculty_PanelLayout = new javax.swing.GroupLayout(add_Assignment_Faculty_Panel);
        add_Assignment_Faculty_Panel.setLayout(add_Assignment_Faculty_PanelLayout);
        add_Assignment_Faculty_PanelLayout.setHorizontalGroup(
                add_Assignment_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Assignment_Faculty_PanelLayout.createSequentialGroup()
                                .addGap(412, 412, 412)
                                .addComponent(jLabel10)
                                .addContainerGap(419, Short.MAX_VALUE))
        );
        add_Assignment_Faculty_PanelLayout.setVerticalGroup(
                add_Assignment_Faculty_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(add_Assignment_Faculty_PanelLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel10)
                                .addContainerGap(265, Short.MAX_VALUE))
        );

        jLabel11.setText("assignment faculty list");

        javax.swing.GroupLayout assignment_Faculty_List_PanelLayout = new javax.swing.GroupLayout(assignment_Faculty_List_Panel);
        assignment_Faculty_List_Panel.setLayout(assignment_Faculty_List_PanelLayout);
        assignment_Faculty_List_PanelLayout.setHorizontalGroup(
                assignment_Faculty_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(assignment_Faculty_List_PanelLayout.createSequentialGroup()
                                .addGap(415, 415, 415)
                                .addComponent(jLabel11)
                                .addContainerGap(423, Short.MAX_VALUE))
        );
        assignment_Faculty_List_PanelLayout.setVerticalGroup(
                assignment_Faculty_List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(assignment_Faculty_List_PanelLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(jLabel11)
                                .addContainerGap(257, Short.MAX_VALUE))
        );

        layered_Panel.setLayer(home_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(add_Faculty_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(faculty_List_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(add_Student_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(student_List_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(add_Course_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(course_List_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(add_Subject_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(subject_List_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(add_Assignment_Faculty_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered_Panel.setLayer(assignment_Faculty_List_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layered_PanelLayout = new javax.swing.GroupLayout(layered_Panel);
        layered_Panel.setLayout(layered_PanelLayout);
        layered_PanelLayout.setHorizontalGroup(
                layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(home_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Faculty_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(faculty_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(add_Student_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(student_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Course_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(course_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Subject_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(subject_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Assignment_Faculty_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(assignment_Faculty_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layered_PanelLayout.setVerticalGroup(
                layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layered_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(home_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Faculty_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(faculty_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Student_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(student_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Course_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(course_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Subject_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(subject_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(add_Assignment_Faculty_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layered_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layered_PanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(assignment_Faculty_List_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        home_Menu.setText("Home");
        home_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_MenuActionPerformed(evt);
            }
        });

        home_MenuItem.setText("Home");
        home_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_MenuItemActionPerformed(evt);
            }
        });
        home_Menu.add(home_MenuItem);

        dashboard_menuBar.add(home_Menu);

        faculty_Menu.setText("Faculty");

        addFaculty_MenuItem.setText("Add Faculty");
        addFaculty_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFaculty_MenuItemActionPerformed(evt);
            }
        });
        faculty_Menu.add(addFaculty_MenuItem);

        FacultyList_MenuItem.setText("Faculty List");
        FacultyList_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyList_MenuItemActionPerformed(evt);
            }
        });
        faculty_Menu.add(FacultyList_MenuItem);

        dashboard_menuBar.add(faculty_Menu);

        student_Menu.setText("Student");

        AddStudent_MenuItem.setText("Add Student");
        AddStudent_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudent_MenuItemActionPerformed(evt);
            }
        });
        student_Menu.add(AddStudent_MenuItem);

        StudentList_MenuItem.setText("Student List");
        StudentList_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentList_MenuItemActionPerformed(evt);
            }
        });
        student_Menu.add(StudentList_MenuItem);

        dashboard_menuBar.add(student_Menu);

        course_Menu.setText("Course");

        AddCourse_MenuItem.setText("Add Course");
        AddCourse_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCourse_MenuItemActionPerformed(evt);
            }
        });
        course_Menu.add(AddCourse_MenuItem);

        CourseList_MenuItem.setText("Course List");
        CourseList_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseList_MenuItemActionPerformed(evt);
            }
        });
        course_Menu.add(CourseList_MenuItem);

        dashboard_menuBar.add(course_Menu);

        subject_Menu.setText("Subject");

        AddSubject_MenuItem.setText("Add Subject");
        AddSubject_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubject_MenuItemActionPerformed(evt);
            }
        });
        subject_Menu.add(AddSubject_MenuItem);

        SubjectList_MenuItem.setText("Subject List");
        SubjectList_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectList_MenuItemActionPerformed(evt);
            }
        });
        subject_Menu.add(SubjectList_MenuItem);

        dashboard_menuBar.add(subject_Menu);

        assignmentFaculty_Menu.setText("Assignment Faculty");

        AddAssignmentFaculty_MenuItem.setText("Add Assignment Faculty");
        AddAssignmentFaculty_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAssignmentFaculty_MenuItemActionPerformed(evt);
            }
        });
        assignmentFaculty_Menu.add(AddAssignmentFaculty_MenuItem);

        AssignmentFacultyList_MenuItem.setText("Assignment Faculty List");
        AssignmentFacultyList_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignmentFacultyList_MenuItemActionPerformed(evt);
            }
        });
        assignmentFaculty_Menu.add(AssignmentFacultyList_MenuItem);

        dashboard_menuBar.add(assignmentFaculty_Menu);

        setJMenuBar(dashboard_menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(layered_Panel)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(layered_Panel)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void addFaculty_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(true);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);
    }

    private void AddStudent_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(true);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);    }

    private void AddAssignmentFaculty_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(true);
        assignment_Faculty_List_Panel.setVisible(false);    }

    private void home_MenuActionPerformed(java.awt.event.ActionEvent evt) {

        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(true);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);


    }

    private void FacultyList_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(true);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);    }

    private void StudentList_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(true);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);
    }

    private void AddCourse_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(true);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);
    }

    private void CourseList_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(true);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);
    }

    private void AddSubject_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(true);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);    }

    private void SubjectList_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(true);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);    }

    private void AssignmentFacultyList_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(false);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(true);    }

    private void loginID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void mobileNumber_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void firstName_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void gender_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void lastName_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void save_AddFacultyPanel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void home_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        add_Faculty_Panel.setVisible(false);
        home_Panel.setVisible(true);
        faculty_List_Panel.setVisible(false);
        student_List_Panel.setVisible(false);
        add_Student_Panel.setVisible(false);
        add_Course_Panel.setVisible(false);
        course_List_Panel.setVisible(false);
        add_Subject_Panel.setVisible(false);
        subject_List_Panel.setVisible(false);
        add_Assignment_Faculty_Panel.setVisible(false);
        assignment_Faculty_List_Panel.setVisible(false);        // TODO add your handling code here:
    }

    private void firstNameSearch_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void loginIDSearch_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void reset_FacultyList_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void student_email_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void confirmpassword_PasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuItem AddAssignmentFaculty_MenuItem;
    private javax.swing.JMenuItem AddCourse_MenuItem;
    private javax.swing.JMenuItem AddStudent_MenuItem;
    private javax.swing.JMenuItem AddSubject_MenuItem;
    private javax.swing.JMenuItem AssignmentFacultyList_MenuItem;
    private javax.swing.JMenuItem CourseList_MenuItem;
    private javax.swing.JMenuItem FacultyList_MenuItem;
    private javax.swing.JMenuItem StudentList_MenuItem;
    private javax.swing.JMenuItem SubjectList_MenuItem;
    private javax.swing.JMenuItem addFaculty_MenuItem;
    private javax.swing.JPanel add_Assignment_Faculty_Panel;
    private javax.swing.JPanel add_Course_Panel;
    private javax.swing.JPanel add_Faculty_Panel;
    private javax.swing.JPanel add_Student_Panel;
    private javax.swing.JPanel add_Subject_Panel;
    private javax.swing.JMenu assignmentFaculty_Menu;
    private javax.swing.JPanel assignment_Faculty_List_Panel;
    private javax.swing.JPasswordField confirmpassword_PasswordField1;
    private javax.swing.JComboBox<String> courseName_ComboBox;
    private javax.swing.JLabel courseName_Label;
    private javax.swing.JPanel course_List_Panel;
    private javax.swing.JMenu course_Menu;
    private javax.swing.JMenuBar dashboard_menuBar;
    private javax.swing.JButton delete_StudentList_Button;
    private javax.swing.JLabel dob_Label;
    private javax.swing.JTextField dob_TextField;
    private javax.swing.JLabel email_Label;
    private javax.swing.JLabel email_StudentList_Label;
    private javax.swing.JTextField email_StudentList_TextField;
    private javax.swing.JTable facultyList_Table;
    private javax.swing.JPanel faculty_List_Panel;
    private javax.swing.JMenu faculty_Menu;
    private javax.swing.JLabel firstNameSearch_Label;
    private javax.swing.JTextField firstNameSearch_TextField;
    private javax.swing.JLabel firstName_Label;
    private javax.swing.JLabel firstName_StudentList_Label;
    private javax.swing.JTextField firstName_StudentList_TextField;
    private javax.swing.JTextField firstName_TextField1;
    private javax.swing.JComboBox<String> gender_ComboBox;
    private javax.swing.JLabel gender_Label;
    private javax.swing.JMenu home_Menu;
    private javax.swing.JMenuItem home_MenuItem;
    private javax.swing.JPanel home_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lastName_Label;
    private javax.swing.JLabel lastName_StudentList_Label;
    private javax.swing.JTextField lastName_StudentList_TextField;
    private javax.swing.JTextField lastName_TextField1;
    private javax.swing.JLayeredPane layered_Panel;
    private javax.swing.JLabel loginIDSearch_Label;
    private javax.swing.JTextField loginIDSearch_TextField;
    private javax.swing.JTextField loginID_TextField;
    private javax.swing.JTextField mobileNumber_TextField;
    private javax.swing.JButton new_FacultyList_Button;
    private javax.swing.JButton new_StudentList_Button;
    private javax.swing.JLabel parents_Email_Label;
    private javax.swing.JTextField parents_Email_TextField;
    private javax.swing.JLabel parents_Mobile_Label;
    private javax.swing.JTextField parents_mobile_TextField;
    private javax.swing.JLabel password_Label;
    private javax.swing.JPasswordField password_PasswordField;
    private javax.swing.JButton reset_AddFacultyPanel_Button;
    private javax.swing.JButton reset_AddStudent_Button;
    private javax.swing.JButton reset_FacultyList_Button;
    private javax.swing.JButton reset_StudentList_Button;
    private javax.swing.JButton save_AddFacultyPanel_Button;
    private javax.swing.JButton save_AddStudent_Button;
    private javax.swing.JButton search_FacultyList_Button;
    private javax.swing.JButton search_StudentList_Button;
    private javax.swing.JComboBox<String> semester_ComboBox;
    private javax.swing.JLabel semester_Label;
    private javax.swing.JLabel student_ConfirmPassword_Label;
    private javax.swing.JPasswordField student_ConfirmPassword_PasswordField;
    private javax.swing.JLabel student_DateOfBirth_Label;
    private javax.swing.JTextField student_DateOfBirth_TextField;
    private javax.swing.JLabel student_FirstName_Label;
    private javax.swing.JTextField student_FirstName_TextField;
    private javax.swing.JComboBox<String> student_Gender_ComboBox;
    private javax.swing.JLabel student_LastName_Label;
    private javax.swing.JTextField student_LastName_TextField;
    private javax.swing.JPanel student_List_Panel;
    private javax.swing.JMenu student_Menu;
    private javax.swing.JLabel student_MobileNumber_Label;
    private javax.swing.JTextField student_Mobile_TextField;
    private javax.swing.JLabel student_Password_Label;
    private javax.swing.JPasswordField student_Password_PasswordField;
    private javax.swing.JTextField student_email_TextField;
    private javax.swing.JPanel subject_List_Panel;
    private javax.swing.JMenu subject_Menu;
    // End of variables declaration
}
